export const LANDING = '/'
export const ABOUT = 'About'
export const POLICY = 'policy'
export const LOGIN = '/login'
export const SIGNUP = '/signup'
export const RESETPASSWORD = '/reset-password'
export const FORGOTPASSWORD = '/forgot-password'
export const DASHBOARD = '/dashboard'
export const CASES = 'cases'
export const NEWCASES = 'new-case'
export const EXISTINGCASES = 'case'
export const TRACKCASES = 'track-cases'
export const FILLINGS = 'fillings'
export const DRAFTS = 'drafts'
export const FIRMS = 'firms'

